"""Canonical protocol event vocabulary."""

from enum import StrEnum


class EventType(StrEnum):
    GOAL_AMENDED = "goal/amended"
    GOAL_PROPOSED = "goal/proposed"
    AGENT_MESSAGE = "agent/message"
    USER_DIRECTIVE = "user/directive"
    CONTRACT_PREPARED = "contract/prepared"
    CONTRACT_APPROVED = "contract/approved"
    CONTRACT_PATCHED = "contract/patched"
    CONTRACT_PAUSED = "contract/paused"
    CONTRACT_RESUMED = "contract/resumed"
    CONTRACT_CANCELLED = "contract/cancelled"
    CONTRACT_EXPIRED = "contract/expired"
    CONTRACT_BLOCKED = "contract/blocked"
    CONTRACT_COMPLETED = "contract/completed"
    CONTRACT_SATISFIED = "contract/satisfied"
    CONTRACT_ARBITRATED = "contract/arbitrated"
    CONTRACT_REVISION = "contract/revision"
    ATTEMPT_ADMITTED = "attempt/admitted"
    ATTEMPT_STARTED = "attempt/started"
    ATTEMPT_SUCCEEDED = "attempt/succeeded"
    ATTEMPT_FAILED = "attempt/failed"
    ATTEMPT_CANCELLED = "attempt/cancelled"
    ATTEMPT_STALE = "attempt/stale"
    ATTEMPT_ORPHANED = "attempt/orphaned"
    ATTEMPT_WRITE_BACK = "attempt/write-back"
    ATTEMPT_RESUMED = "attempt/resumed"
    DEADLINE_STATUS_CHANGED = "deadline/status-changed"
    ACCEPTANCE_STATUS_CHANGED = "acceptance/status-changed"
    ACCEPTANCE_CALIBRATED = "acceptance/calibrated"
    DECISION_RECORDED = "decision/recorded"
    LEASE_ACQUIRED = "lease/acquired"
    LEASE_RENEWED = "lease/renewed"
    LEASE_RELEASED = "lease/released"
    LEASE_RECLAIMED = "lease/reclaimed"
    LEASE_FENCED = "lease/fenced"
    LEASE_PARTITION_CONFLICT = "lease/partition-conflict"
    CONTEXT_POLICY_APPROVED = "context/policy-approved"
    CONTEXT_SNAPSHOT_BUILT = "context/snapshot-built"
    CONTEXT_SNAPSHOT_EXPIRED = "context/snapshot-expired"
    CONTEXT_SCRATCH_UPDATED = "context/scratch-updated"
    CONTEXT_PROMOTION_REQUESTED = "context/promotion-requested"
    CONTEXT_PROMOTION_ACCEPTED = "context/promotion-accepted"
    CONTEXT_PROMOTION_REJECTED = "context/promotion-rejected"
    CONTEXT_CAPACITY_REFUSED = "context/capacity-refused"
    CONTEXT_REBUILT = "context/rebuilt"
    HANDOVER_INCOMPLETE = "handover/incomplete"
    HANDOVER_DUE = "handover/due"
    PROJECTION_REBUILT = "projection/rebuilt"
    PROJECTION_DIRTY = "projection/dirty"
    STORE_TAMPERED = "store/tampered"
    ESCALATION_REMINDED = "escalation/reminded"
    ESCALATION_STEERED = "escalation/steered"
    ESCALATION_SPAWNED = "escalation/spawned"
    ESCALATION_PARALLELIZED = "escalation/parallelized"
    ESCALATION_HANDED_TO_USER = "escalation/handed-to-user"
    VERIFICATION_REQUESTED = "verification/requested"
    VERIFICATION_CONSUMED = "verification/consumed"
    VERIFICATION_STARTED = "verification/started"
    DISPATCH_REFUSED = "dispatch/refused"
    DISPATCH_DEFERRED = "dispatch/deferred"
    HANDLE_REGISTERED = "handle/registered"
    RECONCILE_REATTACHED = "reconcile/reattached"
    RECONCILE_COLLECTED = "reconcile/collected"
    RECONCILE_ORPHAN_GRACED = "reconcile/orphan-graced"
    RECONCILE_FENCED_REDISPATCHED = "reconcile/fenced-redispatched"
    CHECKPOINT_BUILT = "checkpoint/built"
    CAPSULE_BUILT = "capsule/built"
    FORECAST_UPDATED = "forecast/updated"
    NEXT_DECISION_AT_SET = "next-decision/set"
    NOTIFY_DISPATCHED = "notify/dispatched"
    WAKEUP_SLEEP_GUARD = "wakeup/sleep-guard"
    WAKEUP_RTC_ARMED = "wakeup/rtc-armed"
    WAKEUP_RTC_FIRED = "wakeup/rtc-fired"
    WAKEUP_DEGRADED = "wakeup/degraded"
    # ── P6：反馈回路 / 多合同组合 / deadline 多级升级 ──
    USER_EVALUATION_SUBMITTED = "user/evaluation-submitted"
    ACCEPTANCE_DIFF_COMPUTED = "acceptance/diff-computed"
    DEADLINE_LEVEL_ESCALATED = "deadline/level-escalated"
    DEADLINE_BREACH_LOCKED = "deadline/breach-locked"
    PORTFOLIO_SUMMARY_VIEWED = "portfolio/summary-viewed"
    TEMPLATE_EVOLVED = "template/evolved"
    MEMORY_EXPIRED = "memory/expired"
    MEMORY_AUTO_MINED = "memory/auto-mined"
    MEMORY_AUTO_MINE_FAILED = "memory/auto-mine-failed"
    MEMORY_LESSON_MINED = "memory/lesson-mined"
    # ── Resilient contract execution ──
    RETRY_ATTEMPTED = "retry/attempted"
    PLAN_SUBMITTED = "plan/submitted"
    PLAN_APPROVED = "plan/approved"
    PLAN_REJECTED = "plan/rejected"


__all__ = ["EventType"]
